language: node_js
sudo: false
node_js:
- '4'
branches:
  only:
  - master
  - /^v\d+(\.\d+)*$/
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
script:
- git clone https://github.com/QwantResearch/qwant-basic-gl-style.git
- cd gl-style-package-spec
- npm run build_all -- --style_dir=../style --conf=../maps-tileview/config/map_dev.json
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: build/${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
